name: Publish PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Github Commit Timestamp Tagger
      uses: mcpierce/github-commit-timestamp-tagger@0.0.1
    - name: Render PDF
      run: npx markdown-pdf -f Letter -o resume.pdf ./readme.md
    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        files: resume.pdf
      env:
        CI: true
